name: Build & Test
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Restore NuGet Packages
      run: nuget restore CourseCrawler.sln
 
    - name: Build
      run: msbuild CourseCrawler.sln /p:Configuration=Release
      
#       Since the GUI test is too ugly, we decided not to do this check forever... :(
#     - name: Setup VSTest
#       uses: darenm/Setup-VSTest@v1
      
#     - name: Run Tests
#       run: vstest.console.exe .\CourseCrawlerTest\bin\Release\CourseCrawlerTest.dll
